### ISSUE TITLE
ltk.Switch always starts True (demo)

### ISSUE THREAD

**Issue by Neon22** [pyscript/ltk#10]
The Switch always shows as on whether initialised with True or False.
E.g. `ltk.Switch("Foo",False)` and `ltk.Switch("Foo",True)`
Demo here:
- https://pyscript.com/@neon22/ltk-switch-broken/latest

So Switch works ok just doesn't show correct state on initialization.

**Comment by Neon22** [comment]
Well to be clearer - if probed it is holding as True even if initialized false.
So the switch is showing what it thinks is the correct value.

Its purely an initialization problem (IMHO).

**Comment by laffra** [comment]
What a coincidence. I ran into this myself last week. A commit with a fix was pushed 5 days ago: https://github.com/pyscript/ltk/commit/198c2a4cbb79c2480bea09363ae72378f94c0ad9

I just cut a new release on pypi to pick this up. I forgot to do that last week.

Your example now shows the expected result?

![Screenshot 2024-07-20 at 8 48 10 AM](https://github.com/user-attachments/assets/79388865-f657-4b5b-ab45-1a4b36a10aca)

**Comment by Neon22** [comment]
wow. Thanks Chris. cheers
