### ISSUE TITLE
ImportError: cannot import name 'document' from 'pyscript' 

### ISSUE THREAD

**Issue by maphew** [pyscript/ltk#12]
Newbie here, I can't get the Hello World example to work. I'm on Windows 11 with python 3.13.

```py
import ltk
ltk.Text("Hello World").appendTo(ltk.body)
```

yields:
```pwsh
A:\code\meltok> python .\src\meltok\hello.py
Traceback (most recent call last):
  File "A:\code\meltok\src\meltok\hello.py", line 1, in <module>
    import ltk
  File "A:\code\meltok\.pixi\envs\default\Lib\site-packages\ltk\__init__.py", line 3, in <module>
    from ltk.jquery import *
  File "A:\code\meltok\.pixi\envs\default\Lib\site-packages\ltk\jquery.py", line 4, in <module>
    from pyscript import document # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'document' from 'pyscript' (A:\code\meltok\.pixi\envs\default\Lib\site-packages\pyscript\__init__.py)
```

I'm using Pixi environment and package manage from Prefix.dev, so that might be at play. The python packages in the env according to pip are below, and the conda package list is attached after that.

```
> pip list
Package            Version   Editable project location
------------------ --------- -------------------------
certifi            2024.8.30
charset-normalizer 3.4.0
click              8.1.7
colorama           0.4.6
idna               3.10
Jinja2             3.1.4
markdown-it-py     3.0.0
MarkupSafe         3.0.2
mdurl              0.1.2
meltok             0.1.0     A:\code\meltok
pip                24.3.1
platformdirs       4.2.2
pluggy             1.5.0
Pygments           2.18.0
pyscript           0.3.3
pyscript-ltk       0.1.43
requests           2.31.0
rich               13.7.1
toml               0.10.2
typer              0.9.0
typing_extensions  4.12.2
urllib3            2.2.3
```
[pixi.lock.txt](https://github.com/user-attachments/files/17726197/pixi.lock.txt)

**Comment by laffra** [comment]
You appear to run LTK from the command line on your laptop/desktop. This is not how PyScript applications are launched. A PyScript application is part of a website and runs inside of an HTML file. You can do so from your command line, but it is easier from VS Code, where you can easily preview an index.html. You can also run the PyScript app on a hosted environment, such as pyscript.com. A good example to get started is given in the LTK README: https://github.com/pyscript/ltk?tab=readme-ov-file#getting-started

**Comment by maphew** [comment]
oh! thank you for that context. I'm needing to build something that works with local file system and there is no webserver available. So LTK is not for me at this time. 

Pysheets demos a lot of interesting possibilities though, so LTK bookmarked for a possible future project.
